<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\ProductImage;
use App\Models\ProductVariant;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->products() as $data) {
            $product = Product::updateOrCreate(
                ['slug' => $data['slug']],
                [
                    'name' => $data['name'],
                    'sku' => $data['sku'],
                    'short_description' => $data['short_description'],
                    'description' => $data['description'],
                    'highlights' => implode(PHP_EOL, $data['highlights']),
                    'ingredients' => implode(PHP_EOL, $data['ingredients']),
                    'benefits' => implode(PHP_EOL, $data['benefits']),
                    'how_to_use' => implode(PHP_EOL, $data['how_to_use']),
                    'warnings' => $data['warnings'] ?? null,
                    'precautions' => $data['precautions'] ?? null,
                    'disclaimer' => $data['disclaimer'] ?? 'For external use only. Keep out of reach of children. Discontinue use if irritation occurs.',
                    'net_quantity' => $data['net_quantity'],
                    'unit' => $data['unit'],
                    'mrp' => $data['mrp'],
                    'selling_price' => $data['selling_price'],
                    'discount_percent' => round((($data['mrp'] - $data['selling_price']) / $data['mrp']) * 100, 1),
                    'gst_rate' => $data['gst_rate'],
                    'stock' => $data['stock'],
                    'low_stock_threshold' => $data['low_stock_threshold'] ?? 5,
                    'hsn_code' => $data['hsn_code'],
                    'manufacturer' => 'VANRITI Naturals Pvt. Ltd., Plot 21, Sector 62, Gurugram, Haryana 122102',
                    'manufacturer_address' => 'Plot 21, Sector 62, Gurugram, Haryana 122102',
                    'country_of_origin' => 'India',
                    'shelf_life' => '24 months from date of manufacture',
                    'meta_title' => $data['name'].' | VANRITI',
                    'meta_description' => $data['short_description'],
                    'meta_keywords' => Str::slug($data['name']).', vanriti, herbal, ayurvedic',
                    'search_keywords' => $data['search_keywords'],
                    'status' => $data['status'] ?? 'active',
                    'is_featured' => $data['is_featured'] ?? false,
                    'is_bestseller' => $data['is_bestseller'] ?? false,
                    'is_new_arrival' => $data['is_new_arrival'] ?? false,
                    'total_sold' => $data['total_sold'] ?? 0,
                ]
            );

            $category = \App\Models\Category::where('slug', $data['category_slug'])->first();
            if ($category) {
                $product->categories()->syncWithoutDetaching([$category->id => ['is_primary' => true]]);
            }

            if ($product->images()->count() === 0) {
                $colors = ['/1f3d2b/f7f4ee', '/4a7c3f/ffffff', '/8a9a5b/ffffff'];
                foreach (range(1, 3) as $i) {
                    ProductImage::create([
                        'product_id' => $product->id,
                        'image_path' => 'https://placehold.co/600x600'.$colors[$i - 1].'/png?text='.Str::upper($product->slug),
                        'alt_text' => $product->name,
                        'type' => $i === 1 ? 'main' : 'gallery',
                        'sort_order' => $i,
                    ]);
                }
            }

            if (! empty($data['variants'])) {
                foreach ($data['variants'] as $sort => $variantData) {
                    ProductVariant::updateOrCreate(
                        ['product_id' => $product->id, 'sku' => $variantData['sku']],
                        [
                            'name' => $variantData['name'],
                            'mrp' => $variantData['mrp'],
                            'selling_price' => $variantData['selling_price'],
                            'discount_percent' => round((($variantData['mrp'] - $variantData['selling_price']) / $variantData['mrp']) * 100, 1),
                            'stock' => $variantData['stock'],
                            'low_stock_threshold' => 5,
                            'weight' => $variantData['weight'],
                            'gst_rate' => $data['gst_rate'],
                            'status' => 'active',
                            'is_default' => $sort === 0,
                            'sort_order' => $sort,
                        ]
                    );
                }
            }
        }
    }

    protected function products(): array
    {
        return [
            [
                'name' => 'Aloe Vera & Green Tea Face Wash',
                'slug' => 'aloe-vera-green-tea-face-wash',
                'sku' => 'VR-FW-001',
                'category_slug' => 'face-cleansers',
                'short_description' => 'A gentle foaming face wash that clears excess oil and impurities without stripping natural moisture.',
                'description' => 'Powered by certified aloe vera gel and antioxidant-rich green tea extract, this pH-balanced face wash dissolves daily grime, fights shine and leaves skin feeling refreshed and soft. Sulphate-free and kind to sensitive skin.',
                'highlights' => ['Sulphate-free and paraben-free', 'Balances oil without over-drying', 'Enriched with aloe vera and green tea'],
                'ingredients' => ['Aloe vera gel', 'Green tea extract', 'Coconut-derived cleansers', 'Glycerin', 'Neem oil'],
                'benefits' => ['Removes excess oil', 'Soothes and calms skin', 'Leaves a clean, non-tight feel'],
                'how_to_use' => ['Wet your face', 'Massage a small amount on damp skin', 'Rinse thoroughly and pat dry', 'Use twice daily'],
                'net_quantity' => '150 ml',
                'unit' => 'ml',
                'mrp' => 349.00,
                'selling_price' => 249.00,
                'gst_rate' => 18,
                'stock' => 120,
                'hsn_code' => '3304',
                'search_keywords' => 'face wash, aloe cleanser, oily skin face wash, green tea face wash',
                'is_featured' => true,
                'is_bestseller' => true,
                'total_sold' => 842,
            ],
            [
                'name' => 'Vitamin C Brightening Serum 15%',
                'slug' => 'vitamin-c-brightening-serum',
                'sku' => 'VR-ST-014',
                'category_slug' => 'serums-treatments',
                'short_description' => 'A stable 15% vitamin C serum with niacinamide and hyaluronic acid to brighten, even tone and plump skin.',
                'description' => 'Encapsulated vitamin C works deep to fade dullness and dark spots while niacinamide refines pores and hyaluronic acid locks in hydration. Lightweight, fast-absorbing and layered easily under sunscreen.',
                'highlights' => ['15% stabilised vitamin C', 'Niacinamide + hyaluronic acid', 'Fragrance-free formulation'],
                'ingredients' => ['Ascorbyl glucoside (15%)', 'Niacinamide (5%)', 'Hyaluronic acid', 'Green tea extract', 'Vitamin E'],
                'benefits' => ['Brightens dull skin', 'Reduces dark spots', 'Improves skin elasticity'],
                'how_to_use' => ['Apply 3-4 drops on clean skin', 'Gently massage until absorbed', 'Follow with sunscreen in the morning'],
                'warnings' => 'For topical use only. Avoid contact with eyes.',
                'precautions' => 'In case of redness, reduce frequency to alternate days.',
                'net_quantity' => '30 ml',
                'unit' => 'ml',
                'mrp' => 799.00,
                'selling_price' => 599.00,
                'gst_rate' => 18,
                'stock' => 85,
                'hsn_code' => '3304',
                'search_keywords' => 'vitamin c serum, brightening serum, dark spots, glow serum',
                'is_featured' => true,
                'is_new_arrival' => true,
                'total_sold' => 512,
            ],
            [
                'name' => 'Kumkumadi Brightening Face Oil',
                'slug' => 'kumkumadi-brightening-face-oil',
                'sku' => 'VR-ST-021',
                'category_slug' => 'serums-treatments',
                'short_description' => 'The classic ayurvedic Kumkumadi oil with saffron and manjistha, reimagined for daily glow.',
                'description' => 'An ancient ayurvedic elixir blending kesar (saffron), manjistha and lotus seed in cold-pressed sesame oil. Helps improve complexion, reduces dark spots and leaves a natural luminous veil.',
                'highlights' => ['Ayurvedic Kumkumadi classic', 'Saffron + manjistha actives', 'Cold-pressed oil base'],
                'ingredients' => ['Saffron', 'Manjistha', 'Lotus seed', 'Vetiver', 'Cold-pressed sesame oil'],
                'benefits' => ['Improves overall complexion', 'Reduces dark spots', 'Adds dewy radiance'],
                'how_to_use' => ['Warm 3-4 drops', 'Massage on face and neck gently', 'Use at night for best results'],
                'net_quantity' => '20 ml',
                'unit' => 'ml',
                'mrp' => 649.00,
                'selling_price' => 499.00,
                'gst_rate' => 12,
                'stock' => 60,
                'hsn_code' => '3304',
                'search_keywords' => 'kumkumadi oil, ayurvedic face oil, saffron oil, glowing skin',
                'is_featured' => true,
                'is_bestseller' => true,
                'total_sold' => 640,
            ],
            [
                'name' => 'SPF 50 Mineral Sunscreen Gel',
                'slug' => 'spf-50-mineral-sunscreen-gel',
                'sku' => 'VR-SC-009',
                'category_slug' => 'sun-care',
                'short_description' => 'A weightless, non-sticky mineral sunscreen with SPF 50 PA++++ that leaves no white cast.',
                'description' => 'Zinc-based broad-spectrum protection blended with aloe vera and vitamin E. Blends invisibly into all skin tones, works beautifully under makeup and is gentle enough for sensitive skin.',
                'highlights' => ['SPF 50 PA++++ broad spectrum', 'No white cast', 'Non-comedogenic, silicone-free'],
                'ingredients' => ['Zinc oxide (21%)', 'Aloe vera', 'Vitamin E', 'Glycerin'],
                'benefits' => ['Protects against UVA/UVB', 'Prevents tanning and photodamage', 'Hydrates while protecting'],
                'how_to_use' => ['Apply generously 15 minutes before sun exposure', 'Reapply every 2 hours', 'Use as the last step of your routine'],
                'net_quantity' => '50 g',
                'unit' => 'g',
                'mrp' => 549.00,
                'selling_price' => 429.00,
                'gst_rate' => 18,
                'stock' => 110,
                'hsn_code' => '3304',
                'search_keywords' => 'sunscreen, spf 50, mineral sunscreen, sunscreen gel, no white cast',
                'is_featured' => true,
                'is_new_arrival' => true,
                'total_sold' => 389,
            ],
            [
                'name' => 'Bhringraj & Amla Hair Growth Oil',
                'slug' => 'bhringraj-amla-hair-oil',
                'sku' => 'VR-HO-003',
                'category_slug' => 'hair-oils',
                'short_description' => 'A 12-herb infusion of bhringraj, amla, curry leaves and coconut oil for stronger, longer hair.',
                'description' => 'Traditional herbs slow-infused in cold-pressed coconut oil. Nourishes the scalp, reduces hair fall and deeply conditions from root to tip. Dermatologically tested and free from mineral oil.',
                'highlights' => ['12 ayurvedic herbs', 'Reduces hair fall', 'No mineral oil, no silicones'],
                'ingredients' => ['Bhringraj', 'Amla', 'Curry leaves', 'Brahmi', 'Cold-pressed coconut oil', 'Hibiscus'],
                'benefits' => ['Strengthens roots', 'Reduces hair fall', 'Adds natural shine'],
                'how_to_use' => ['Massage oil into scalp for 10 minutes', 'Leave for 1 hour or overnight', 'Wash with a mild shampoo'],
                'net_quantity' => '200 ml',
                'unit' => 'ml',
                'mrp' => 449.00,
                'selling_price' => 339.00,
                'gst_rate' => 18,
                'stock' => 150,
                'hsn_code' => '3305',
                'search_keywords' => 'hair oil, bhringraj oil, amla oil, hair fall oil, ayurvedic hair oil',
                'is_featured' => true,
                'is_bestseller' => true,
                'total_sold' => 1204,
                'variants' => [
                    ['name' => '100 ml', 'sku' => 'VR-HO-003-100', 'mrp' => 299.00, 'selling_price' => 219.00, 'stock' => 80, 'weight' => '100 ml'],
                    ['name' => '200 ml', 'sku' => 'VR-HO-003-200', 'mrp' => 449.00, 'selling_price' => 339.00, 'stock' => 70, 'weight' => '200 ml'],
                ],
                'has_variants' => true,
            ],
            [
                'name' => 'Onion & Olive Strength Shampoo',
                'slug' => 'onion-olive-strength-shampoo',
                'sku' => 'VR-SH-011',
                'category_slug' => 'shampoos',
                'short_description' => 'Sulphate-free shampoo with onion extract and olive oil to fortify thinning, damaged hair.',
                'description' => 'Gentle, sulphate-free cleansing infused with onion extract, biotin and cold-pressed olive oil. Builds volume, reduces breakage and keeps scalp healthy without stripping natural oils.',
                'highlights' => ['Sulphate and paraben free', 'Onion + biotin complex', 'Suitable for daily use'],
                'ingredients' => ['Onion extract', 'Olive oil', 'Biotin', 'Aloe vera', 'Amla'],
                'benefits' => ['Strengthens weak hair', 'Reduces breakage', 'Adds bounce and volume'],
                'how_to_use' => ['Apply on wet hair and lather', 'Massage scalp with fingertips', 'Rinse thoroughly', 'Follow with conditioner'],
                'net_quantity' => '250 ml',
                'unit' => 'ml',
                'mrp' => 399.00,
                'selling_price' => 299.00,
                'gst_rate' => 18,
                'stock' => 95,
                'hsn_code' => '3305',
                'search_keywords' => 'shampoo, onion shampoo, sulphate free shampoo, hair fall shampoo',
                'is_featured' => true,
                'is_new_arrival' => true,
                'total_sold' => 455,
            ],
            [
                'name' => 'Rose & Shea Body Butter',
                'slug' => 'rose-shea-body-butter',
                'sku' => 'VR-BL-006',
                'category_slug' => 'body-lotions-butters',
                'short_description' => 'Whipped shea and rose butter that melts into skin for 24-hour deep nourishment.',
                'description' => 'A rich, fast-absorbing body butter with unrefined shea, rose petal extract and vitamin E. Restores elasticity, smooths dry patches and leaves a subtle rose veil.',
                'highlights' => ['Unrefined shea butter base', 'Rose petal extract', 'Dermatologically tested'],
                'ingredients' => ['Unrefined shea butter', 'Rose extract', 'Vitamin E', 'Sweet almond oil'],
                'benefits' => ['Deep 24-hour hydration', 'Smooths dry patches', 'Leaves soft, dewy skin'],
                'how_to_use' => ['Scoop a small amount', 'Massage onto body, focusing on dry areas', 'Use daily after shower'],
                'net_quantity' => '200 g',
                'unit' => 'g',
                'mrp' => 499.00,
                'selling_price' => 379.00,
                'gst_rate' => 18,
                'stock' => 70,
                'hsn_code' => '3304',
                'search_keywords' => 'body butter, shea butter, dry skin cream, rose body butter',
                'is_featured' => true,
                'total_sold' => 328,
            ],
            [
                'name' => 'Coffee & Walnut Body Scrub',
                'slug' => 'coffee-walnut-body-scrub',
                'sku' => 'VR-BS-002',
                'category_slug' => 'body-scrubs',
                'short_description' => 'Energising scrub with arabica coffee grounds and walnut shell to polish skin and boost circulation.',
                'description' => 'Invigorating pre-shower scrub that buffs away dullness, smooths bumps and refines skin texture. Coffee stimulates circulation while walnut gently exfoliates.',
                'highlights' => ['Arabica coffee grounds', 'Walnut shell exfoliation', 'Boosts circulation'],
                'ingredients' => ['Coffee grounds', 'Walnut shell', 'Coconut oil', 'Brown sugar', 'Vitamin E'],
                'benefits' => ['Smooths and polishes', 'Improves skin texture', 'Revives tired skin'],
                'how_to_use' => ['Massage on damp skin in circular motions', 'Focus on elbows, knees and heels', 'Rinse off and follow with body butter'],
                'net_quantity' => '250 g',
                'unit' => 'g',
                'mrp' => 449.00,
                'selling_price' => 349.00,
                'gst_rate' => 18,
                'stock' => 55,
                'hsn_code' => '3304',
                'search_keywords' => 'body scrub, coffee scrub, exfoliating scrub, walnut scrub',
                'is_bestseller' => true,
                'total_sold' => 610,
            ],
            [
                'name' => 'Ashwagandha Daily Wellness Capsules',
                'slug' => 'ashwagandha-daily-wellness-capsules',
                'sku' => 'VR-SU-021',
                'category_slug' => 'vitamins-supplements',
                'short_description' => 'KSM-66 ashwagandha capsules for everyday stress support, energy and restful sleep.',
                'description' => 'Standardised KSM-66 full-spectrum ashwagandha root extract in a clean, vegetarian capsule. Supports stress balance, physical endurance and natural sleep quality.',
                'highlights' => ['KSM-66 full-spectrum extract', '60 vegetarian capsules', 'Third-party lab tested'],
                'ingredients' => ['KSM-66 ashwagandha root extract (5% withanolides)'],
                'benefits' => ['Supports stress balance', 'Aids restful sleep', 'Boosts everyday energy'],
                'how_to_use' => ['Take 1 capsule twice daily with water', 'Continue for 60 days for best results', 'Best taken after meals'],
                'warnings' => 'Not recommended for pregnant or nursing women. Consult a physician before use.',
                'net_quantity' => '60 capsules',
                'unit' => 'capsules',
                'mrp' => 599.00,
                'selling_price' => 449.00,
                'gst_rate' => 12,
                'stock' => 130,
                'hsn_code' => '3004',
                'search_keywords' => 'ashwagandha, stress support, capsules, wellness, ksm66',
                'is_featured' => true,
                'is_bestseller' => true,
                'total_sold' => 935,
                'disclaimer' => 'This product is not intended to diagnose, treat, cure or prevent any disease.',
            ],
            [
                'name' => 'Tulsi, Amla & Turmeric Immunity Booster',
                'slug' => 'tulsi-amla-turmeric-immunity-booster',
                'sku' => 'VR-IB-003',
                'category_slug' => 'immunity-boosters',
                'short_description' => 'A daily ayurvedic blend of tulsi, amla and turmeric oleoresin to support natural immunity.',
                'description' => 'Traditional herbs celebrated across Indian households, slow-brewed into an easy daily tonic. Tulsi soothes, amla provides vitamin C and turmeric oleoresin brings antioxidant support.',
                'highlights' => ['Triple-herb ayurvedic blend', 'Natural vitamin C from amla', 'Antioxidant rich'],
                'ingredients' => ['Tulsi extract', 'Amla extract', 'Turmeric oleoresin', 'Black pepper', 'Honey'],
                'benefits' => ['Supports natural immunity', 'Antioxidant support', 'Soothes and refreshes'],
                'how_to_use' => ['Mix 10 ml in warm water', 'Take once daily in the morning', 'Shake bottle before use'],
                'warnings' => 'Not recommended for pregnant or nursing women. Consult a physician for pre-existing conditions.',
                'net_quantity' => '200 ml',
                'unit' => 'ml',
                'mrp' => 499.00,
                'selling_price' => 379.00,
                'gst_rate' => 12,
                'stock' => 140,
                'hsn_code' => '3004',
                'search_keywords' => 'immunity booster, tulsi, amla, turmeric, ayurvedic tonic',
                'is_featured' => true,
                'is_new_arrival' => true,
                'total_sold' => 512,
                'disclaimer' => 'This product is not intended to diagnose, treat, cure or prevent any disease.',
            ],
            [
                'name' => 'Calming Chamomile & Lavender Herbal Tea',
                'slug' => 'calming-chamomile-lavender-tea',
                'sku' => 'VR-TEA-001',
                'category_slug' => 'sleep-relaxation',
                'short_description' => 'A caffeine-free evening blend of chamomile, lavender and lemon balm for restful wind-down.',
                'description' => 'Winding down starts here. A fragrant, caffeine-free cup of chamomile flowers, lavender and lemon balm helps ease the mind after a long day.',
                'highlights' => ['100% caffeine-free', 'Zero added sugar', 'Loose leaf, biodegradable pouch'],
                'ingredients' => ['Chamomile flowers', 'Lavender buds', 'Lemon balm', 'Rose petals'],
                'benefits' => ['Encourages relaxation', 'Supports restful sleep', 'Naturally caffeine-free'],
                'how_to_use' => ['Steep 1 tsp in hot water for 5 minutes', 'Strain and sip slowly', 'Enjoy 30 minutes before bed'],
                'net_quantity' => '75 g',
                'unit' => 'g',
                'mrp' => 349.00,
                'selling_price' => 269.00,
                'gst_rate' => 5,
                'stock' => 90,
                'hsn_code' => '0902',
                'search_keywords' => 'herbal tea, chamomile tea, sleep tea, lavender tea, caffeine free',
                'is_bestseller' => true,
                'total_sold' => 421,
            ],
            [
                'name' => 'Gentle Baby Wash with Calendula',
                'slug' => 'gentle-baby-wash-calendula',
                'sku' => 'VR-BB-004',
                'category_slug' => 'baby-bath-body',
                'short_description' => 'A tear-free, soap-free baby wash with calendula and chamomile that cleanses gently.',
                'description' => 'Formulated for delicate newborn skin with plant-based cleansers, calendula and chamomile. Tear-free, soap-free and pH-balanced to protect the skin barrier.',
                'highlights' => ['Tear-free and soap-free', 'Calendula + chamomile', 'pH balanced for baby skin'],
                'ingredients' => ['Calendula extract', 'Chamomile', 'Coconut-derived cleansers', 'Aloe vera'],
                'benefits' => ['Gently cleanses', 'Protects skin barrier', 'Soothing for delicate skin'],
                'how_to_use' => ['Add a small amount to bath water', 'Gently wash body and hair', 'Rinse and pat dry'],
                'warnings' => 'Keep away from eyes. Discontinue if rash develops.',
                'net_quantity' => '300 ml',
                'unit' => 'ml',
                'mrp' => 399.00,
                'selling_price' => 299.00,
                'gst_rate' => 18,
                'stock' => 75,
                'hsn_code' => '3401',
                'search_keywords' => 'baby wash, baby body wash, calendula baby, tear free baby wash',
                'is_featured' => true,
                'is_new_arrival' => true,
                'total_sold' => 274,
            ],
            [
                'name' => 'Vetiver & Orange Home Fragrance Mist',
                'slug' => 'vetiver-orange-home-fragrance-mist',
                'sku' => 'VR-HF-002',
                'category_slug' => 'home-fragrance',
                'short_description' => 'A fresh room mist of vetiver, neroli and sweet orange to lift any space.',
                'description' => 'Made with essential oils instead of synthetic perfumes. Spritz on linens, curtains and air for an instant mood lift.',
                'highlights' => ['Essential oil based', 'No synthetic perfume', 'Cruelty free'],
                'ingredients' => ['Vetiver essential oil', 'Neroli essential oil', 'Sweet orange essential oil', 'Purified water'],
                'benefits' => ['Freshens any space', 'Lifts mood', 'Safe around family'],
                'how_to_use' => ['Shake well', 'Spritz 2-3 times in the air', 'Use on linens and upholstery'],
                'net_quantity' => '100 ml',
                'unit' => 'ml',
                'mrp' => 449.00,
                'selling_price' => 339.00,
                'gst_rate' => 18,
                'stock' => 65,
                'hsn_code' => '3303',
                'search_keywords' => 'room mist, home fragrance, air freshener, essential oil mist',
                'total_sold' => 198,
            ],
            [
                'name' => 'Kesar & Honey Brightening Face Pack',
                'slug' => 'kesar-honey-brightening-face-pack',
                'sku' => 'VR-FP-007',
                'category_slug' => 'face-masks-packs',
                'short_description' => 'A creamy saffron, honey and sandalwood mask for a lit-from-within glow in 15 minutes.',
                'description' => 'Instant radiance in a tube. Kesar (saffron), raw honey and sandalwood nourish, soften and brighten, leaving skin fresh and luminous.',
                'highlights' => ['Real kesar and honey', '15-minute glow ritual', 'Soap-free creamy base'],
                'ingredients' => ['Saffron', 'Raw honey', 'Sandalwood', 'Milk protein', 'Vitamin E'],
                'benefits' => ['Instant brightening', 'Deeply nourishes', 'Smooths texture'],
                'how_to_use' => ['Apply evenly on cleansed face', 'Relax for 15 minutes', 'Rinse with lukewarm water', 'Use 2-3 times a week'],
                'net_quantity' => '100 g',
                'unit' => 'g',
                'mrp' => 499.00,
                'selling_price' => 379.00,
                'gst_rate' => 18,
                'stock' => 60,
                'hsn_code' => '3304',
                'search_keywords' => 'face pack, face mask, kesar face pack, honey face pack, brightening mask',
                'is_new_arrival' => true,
                'total_sold' => 233,
            ],
        ];
    }
}